### ISSUE TITLE
configFile not loading

### ISSUE THREAD

**Issue by ediamin** [sasstools/grunt-sass-lint#34]
Hi, I'm using v0.2.2. I'm trying to use the yml from [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scss-lint.yml) but the yml file is not loading when I run `grunt sasslint` command. I'm using the exact file that you can get in Bootstrap repo except different indentation settings (4 space)

```
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4
```

My `Gruntfile.js`
```javascript
module.exports = function (grunt) {
    'use strict';

    grunt.initConfig({
        sasslint: {
            options: {
                configFile: '.scss-lint.yml',
            },
            target: ['scss/erp-ui.scss']
        }
    });

    grunt.loadNpmTasks('grunt-sass-lint');
};
```

My directory tree
```
.
├── .scss-lint.yml
├── Gruntfile.js
├── package.json
└── scss
    └── erp-ui.scss
```

If you need to know anything else, please ask. Thank you.
